import React from "react";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Metadata } from "next";
import { THEMES } from "@/constants";
import SidebarProvider from "@/components/sidebar/SidebarProvider";
import NavbarProvider from "@/components/navbar/NavbarProvider";
import QueryProvider from "@/components/queryclient/QueryProvider";
import Footer from "@/components/footer/Footer";

// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="bg-base-200 font-sans text-base-content antialiased"
      >
        <QueryProvider>
          <ThemeProvider themes={THEMES}>
            <SidebarProvider>
              <NavbarProvider>
                <main className="min-h-[calc(100vh-276px)] min-w-90">
                  {/*calc screen - footer height - header -height*/}
                  {children}
                </main>
                <Footer />
              </NavbarProvider>
            </SidebarProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
